export const data = [
  {
    id: 1,
    contact_picture: 'https://reactnative.dev/img/tiny_logo.png',
    first_name: 'Wilson',
    last_name: 'KOMLAN',
    phone_number: '+2289988765',
    country_code: 'TG',
  },
  {
    id: 2,
    contact_picture: 'https://reactnative.dev/img/tiny_logo.png',
    first_name: 'Merveille',
    last_name: 'KOUMEGNANOU',
    phone_number: '+22899065',
    country_code: 'GH',
  },
  {
    id: 3,
    contact_picture:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAAzCAYAAAA6oTAqAAAAEXRFWHRTb2Z0d2FyZQBwbmdjcnVzaEB1SfMAAABQSURBVGje7dSxCQBACARB+2/ab8BEeQNhFi6WSYzYLYudDQYGBgYGBgYGBgYGBgYGBgZmcvDqYGBgmhivGQYGBgYGBgYGBgYGBgYGBgbmQw+P/eMrC5UTVAAAAABJRU5ErkJggg==',
    first_name: 'Jules',
    last_name: 'SANTANA',
    phone_number: '+22894565',
    country_code: 'BN',
  },
  {
    id: 4,
    contact_picture: '',
    first_name: 'Gisele',
    last_name: 'NAGBE',
    phone_number: '+22899449765',
    country_code: 'MD',
  },
  {
    id: 5,
    contact_picture: 'https://reactnative.dev/img/tiny_logo.png',
    first_name: 'Alphonse',
    last_name: 'SEMANOU',
    phone_number: '+2289987005',
    country_code: 'FR',
  },
  {
    id: 11,
    contact_picture: 'https://reactnative.dev/img/tiny_logo.png',
    first_name: 'Wilson',
    last_name: 'KOMLAN',
    phone_number: '+2289988765',
    country_code: 'CA',
  },
  {
    id: 12,
    contact_picture: 'https://reactnative.dev/img/tiny_logo.png',
    first_name: 'Merveille',
    last_name: 'KOUMEGNANOU',
    phone_number: '+22899065',
    country_code: 'BN',
  },
  {
    id: 13,
    contact_picture: 'https://reactnative.dev/img/tiny_logo.png',
    first_name: 'Jules',
    last_name: 'SANTANA',
    phone_number: '+22894565',
  },
  {
    id: 14,
    contact_picture: '',
    first_name: 'Gisele',
    last_name: 'NAGBE',
    phone_number: '+22899449765',
    country_code: 'MR',
  },
  {
    id: 15,
    contact_picture:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAAzCAYAAAA6oTAqAAAAEXRFWHRTb2Z0d2FyZQBwbmdjcnVzaEB1SfMAAABQSURBVGje7dSxCQBACARB+2/ab8BEeQNhFi6WSYzYLYudDQYGBgYGBgYGBgYGBgYGBgZmcvDqYGBgmhivGQYGBgYGBgYGBgYGBgYGBgbmQw+P/eMrC5UTVAAAAABJRU5ErkJggg==',
    first_name: 'Alphonse',
    last_name: 'SEMANOU',
    phone_number: '+2289987005',
    country_code: 'CH',
  },
  {
    id: 21,
    contact_picture: 'https://reactnative.dev/img/tiny_logo.png',
    first_name: 'Wilson',
    last_name: 'KOMLAN',
    phone_number: '+2289988765',
    country_code: 'TG',
  },
  {
    id: 22,
    contact_picture: '',
    first_name: 'Merveille',
    last_name: 'KOUMEGNANOU',
    phone_number: '+22899065',
    country_code: 'RN',
  },
  {
    id: 23,
    contact_picture: 'https://reactnative.dev/img/tiny_logo.png',
    first_name: 'Jules',
    last_name: 'SANTANA',
    phone_number: '+22894565',
    country_code: 'BN',
  },
  {
    id: 24,
    contact_picture: '',
    first_name: 'Gisele',
    last_name: 'NAGBE',
    phone_number: '+22899449765',
    country_code: 'BN',
  },
  {
    id: 25,
    contact_picture: 'https://reactnative.dev/img/tiny_logo.png',
    first_name: 'Alphonse',
    last_name: 'SEMANOU',
    phone_number: '+2289987005',
    country_code: 'BN',
  },
];
